// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrUe7AhRj4fnsqAbvg-vJz0xVYWZE0XeA',
    appId: '1:109884256472:android:08db667a58319e4fa6e7ad',
    messagingSenderId: '109884256472',
    projectId: 'cgpa-calculator-17a00',
    databaseURL: 'https://cgpa-calculator-17a00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cgpa-calculator-17a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-SYLQb7stQeXk4La3UC35axlAWT5peZ4',
    appId: '1:109884256472:ios:a98fbad0df28ad4da6e7ad',
    messagingSenderId: '109884256472',
    projectId: 'cgpa-calculator-17a00',
    databaseURL: 'https://cgpa-calculator-17a00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cgpa-calculator-17a00.appspot.com',
    iosClientId: '109884256472-o50gjv38pufmmap1euqccnsra6n4hfem.apps.googleusercontent.com',
    iosBundleId: 'com.example.cgpaCalculator',
  );
}
